### ISSUE TITLE
Media queries and transform styles don't seem to work

### ISSUE THREAD

**Issue by fax1ty** [jpudysz/react-native-unistyles#294] opened 2024-09-20 15:43 UTC
### Description

```js    
transform: [
      {
        translateY: {
          [mq.only.width(320, 345)]: 40,
          [mq.only.width(345)]: 0,
        },
      }
 ```

### Steps to reproduce

1. Make a component
2. Transform hasn't been applied.

### Unistyles version

2.9.1

### React Native version

0.74.2

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment] 2024-09-20 17:28
Thanks for the report. Next week I want to release new version. I will try to repro!

**Comment by tamangupta1999** [comment] 2024-09-25 17:19
Thanks @jpudysz for this great library. 🙌

**Built-in breakpoints landscape and portrait** also isnt working:

```
    backgroundColor: {
      landscape: theme.colors.background,
      portrait: theme.colors.warning
    },
```

**Comment by jpudysz** [comment] 2024-09-25 17:39
@tamangupta1999 please read the docs, they work **only on mobile when you don't register your own breakpoints**.

**Comment by jpudysz** [comment] 2024-10-02 05:02
@fax1ty I can't reproduce it.

Tested on Android:

1. Console log current screen width with `UnistylesRuntime.screen.width` -> 448
2. Add style to container:

```ts
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        backgroundColor: theme.colors.backgroundColor,
        rowGap: 20,
        transform: [
            {
                translateY: {
                    [mq.only.width(320, 448)]: 200,
                    [mq.only.width(449)]: 0
                }
            }
        ]
    },
```

3. Result:

```
{"alignItems": "center", "backgroundColor": "#ffffff", "flex": 1, "justifyContent": "center", "paddingHorizontal": 20, "rowGap": 20, "transform": [{"translateY": 200}]}
```

Keep in mind that `mq` is resolved in order and has the biggest priority.

**Closed by jpudysz** 2024-10-02 05:02 UTC
